In [ ]:
# csv => list -> Ndarray
         dict -> value를 list -> Ndarray

# Ndarray 는 수치 데이터만


In [13]:
import numpy as np

data = np.array([1,2,3,4,5])
print(data)
print(data.dtype)
print(type(data))
data1 = np.random.randn(2,3)
print(data1)
print(data1.shape)
print(data1.dtype)
data2 = np.zeros(10)
print(data2)
print(data2.dtype)
data3 = np.zeros((2,3),dtype=np.int64)
print(data3)
data4 = np.ones((3,2),dtype=np.int64)
print(data4)


[1 2 3 4 5]
int64
<class 'numpy.ndarray'>
[[-1.19353942  0.38112962  0.2580889 ]
 [ 1.364607   -0.95578963 -0.50614588]]
(2, 3)
float64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
[[0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]
 [1 1]]


In [17]:
import numpy as np

data = np.arange(10,121,10)
print(data)
data[7:10] = 800
print(data.shape)
data = data.reshape(2,6)
print(data)

[ 10  20  30  40  50  60  70  80  90 100 110 120]
(12,)
[[ 10  20  30  40  50  60]
 [ 70 800 800 800 110 120]]


In [24]:
import numpy as np

data = np.array([[1,2,3,4,5],
                 [6,7,8,9,10],
                 [11,12,13,14,15]])
print(data)
print(data[2][3])
print(data[0][1:])
print(data[0])
print(data[[1,2]]) #1번행, 2번행
data[1] = 100
print(data)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
14
[2 3 4 5]
[1 2 3 4 5]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[  1   2   3   4   5]
 [100 100 100 100 100]
 [ 11  12  13  14  15]]


In [29]:
import numpy as np

a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]])
b = a*2
print(b)
c = a * a
print()
print(c)
print()
print(b>c)
print()


[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]

[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]]

[[ True False False False False]
 [False False False False False]
 [False False False False False]]

