In [ ]:
# csv => list -> Ndarray
         dict -> value를 list -> Ndarray

# Ndarray 는 수치 데이터만


In [13]:
import numpy as np

data = np.array([1,2,3,4,5])
print(data)
print(data.dtype)
print(type(data))
data1 = np.random.randn(2,3)
print(data1)
print(data1.shape)
print(data1.dtype)
data2 = np.zeros(10)
print(data2)
print(data2.dtype)
data3 = np.zeros((2,3),dtype=np.int64)
print(data3)
data4 = np.ones((3,2),dtype=np.int64)
print(data4)


[1 2 3 4 5]
int64
<class 'numpy.ndarray'>
[[-1.19353942  0.38112962  0.2580889 ]
 [ 1.364607   -0.95578963 -0.50614588]]
(2, 3)
float64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
[[0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]
 [1 1]]


In [17]:
import numpy as np

data = np.arange(10,121,10)
print(data)
data[7:10] = 800
print(data.shape)
data = data.reshape(2,6)
print(data)

[ 10  20  30  40  50  60  70  80  90 100 110 120]
(12,)
[[ 10  20  30  40  50  60]
 [ 70 800 800 800 110 120]]


In [24]:
import numpy as np

data = np.array([[1,2,3,4,5],
                 [6,7,8,9,10],
                 [11,12,13,14,15]])
print(data)
print(data[2][3])
print(data[0][1:])
print(data[0])
print(data[[1,2]]) #1번행, 2번행
data[1] = 100
print(data)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
14
[2 3 4 5]
[1 2 3 4 5]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[  1   2   3   4   5]
 [100 100 100 100 100]
 [ 11  12  13  14  15]]


In [29]:
import numpy as np

a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]])
b = a*2
print(b)
c = a * a
print()
print(c)
print()
print(b>c)
print()


[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]

[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]]

[[ True False False False False]
 [False False False False False]
 [False False False False False]]



In [48]:
import numpy as np

a = np.array([[1,2,20,45,5],
              [6,15,8,9,10],
              [11,12,13,14,15]])
print(a.sum())
print(a.max())
print('평균',a.mean())
print(a.min())
print(a.max(axis=0)) #행
print(a.max(axis=1)) #열

index1 = np.argmax(a,axis=0)  #인덱스 
print(index1)
index2 = np.argmin(a,axis=0)  #인덱스
print(index2)


186
45
평균 12.4
1
[11 15 20 45 15]
[45 15 15]
[2 1 0 0 2]
[0 0 1 1 0]


In [13]:
import numpy as np

data = np.random.randn(3,4)
print(data)
print(data > 0)

total = (data<0).sum()  #조건이 True 인 것의 갯수
print(total)

data2 = np.where(data>0, 1, -1)
print(data2)

data3 = np.where(data>0, 5, data)
print(data3)



[[-1.58050064  0.26043213 -1.4471682  -0.58510842]
 [ 0.59058866 -0.16441521 -0.75506898  0.53102686]
 [ 0.08621633  0.58139927 -0.96310422  0.50272459]]
[[False  True False False]
 [ True False False  True]
 [ True  True False  True]]
6
[[-1  1 -1 -1]
 [ 1 -1 -1  1]
 [ 1  1 -1  1]]
[[-1.58050064  5.         -1.4471682  -0.58510842]
 [ 5.         -0.16441521 -0.75506898  5.        ]
 [ 5.          5.         -0.96310422  5.        ]]


In [16]:
import numpy as np

data = np.array([[13,22,17,2],
                 [-2,20,8,3],
                 [-16,10,-5,33]])

print(data)
data.sort(0)
print(data)
data.sort(1)
print(data)


[[ 13  22  17   2]
 [ -2  20   8   3]
 [-16  10  -5  33]]
[[-16  10  -5   2]
 [ -2  20   8   3]
 [ 13  22  17  33]]
[[-16  -5   2  10]
 [ -2   3   8  20]
 [ 13  17  22  33]]


In [21]:
import numpy as np

a = np.arange(10)
print(a)

b = np.insert(a,3,10)
print(b)

c = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]])

print(c)
d = np.insert(c,1,10,axis=0)
print(d)

e = np.insert(c,1,20,axis=1)
print(e)



[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 10  3  4  5  6  7  8  9]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5]
 [10 10 10 10 10]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1 20  2  3  4  5]
 [ 6 20  7  8  9 10]
 [11 20 12 13 14 15]]


In [ ]:
# school_2019.csv

In [43]:
import csv

f = open('school_2019.csv','r',encoding='utf-8')
lines = csv.reader(f)

header = next(lines)
print(header)

list_data = []
for line in lines:
    list_data.append(line[:])

print('-'*50)
length = len(list_data)

data = np.zeros((length,3), dtype='int64')

for i in range(length):
    for j in range(3):
        data[i][j] = int(list_data[i][j+2])


print(data)
print('-'*50)

max_index = np.argmax(data,axis=0)
print(max_index)
max_class = list_data[max_index[0]][1]
print(max_class)
f.close()

['지역', '학교명', '학급수', '학생수', '교사수']
--------------------------------------------------
[[ 28 616  32]
 [ 31 632  35]
 [ 31 837  38]
 ...
 [ 36 985  42]
 [ 34 862  41]
 [ 26 603  31]]
--------------------------------------------------
[ 138 1999  138]
서울신정초등학교


In [58]:
#실습) 예제-14에 최소 학급수/학생수/교사수를 가지는 서울 소재 학교의 이름과 인원수를 출력
# 서울 소재 초등학교 만 발췌해서 Ndarray 생성 먼저 할 것

import csv
import numpy as np

f = open('school_2019.csv','r',encoding='utf-8')
lines = csv.reader(f)

header = next(lines)

list_data = []
for line in lines:
    if '서울' in line[0]:
        list_data.append(line[:])

length = len(list_data)
data = np.zeros((length,3), dtype='int64')
for i in range(length):
    for j in range(3):
        data[i][j] = int(list_data[i][j+2])

min_index = np.argmin(data,axis = 0)
print(min_index)
min_class = list_data[min_index[0]][1] 
min_num = list_data[min_index[0]][2]
print('최소 학급수를 가지는 학교명: {0}, 학급수: {1}'.format(min_class,min_num))

min_student = list_data[min_index[1]][1] 
min_num = list_data[min_index[1]][3]
print('최소 학생수를 가지는 학교명: {0}, 학생수: {1}'.format(min_student,min_num))

min_teacher = list_data[min_index[2]][1] 
min_num = list_data[min_index[2]][4]
print('최소 교사수를 가지는 학교명: {0}, 교사수: {1}'.format(min_teacher,min_num))




[536 276 160]
최소 학급수를 가지는 학교명: 운현초등학교, 학급수: 6
최소 학생수를 가지는 학교명: 서울본동초등학교, 학생수: 102
최소 교사수를 가지는 학교명: 유석초등학교, 교사수: 11
